channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - pip:
      - pynvim
      - networkx
      - invoke
      - click
      - jinja2
      - pydot
      - git-review
      - pylint
      - rope
      - yapf
      - autopep8
  - cmake=3.17.0
  - ninja=1.10.0
